name:                buttplug
version:             0.1.0.0
github:              "githubuser/buttplug"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/buttplug#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- buttplug-hs-core
- containers
- exceptions
- monad-control
- mtl
- stm
- text
- transformers
- transformers-base
- unliftio-core

library:
  source-dirs: src

executables:
  buttplug-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buttplug

tests:
  buttplug-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buttplug
